# frozen_string_literal: true

# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = Rails.application.credentials.public_mailjet.to_s
  config.secret_key = Rails.application.credentials.private_mailjet.to_s
  config.default_from = 'jonathan.mete@hotmail.fr'
end
